CREATE DATABASE IF NOT EXISTS `landslide_analysis`
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

USE `landslide_analysis`;

CREATE TABLE IF NOT EXISTS `raw_data` (
  `raw_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Event_ID` VARCHAR(20) NULL,
  `Date` DATE NULL,
  `State` VARCHAR(100) NULL,
  `District` VARCHAR(100) NULL,
  `Latitude` DECIMAL(10,6) NULL,
  `Longitude` DECIMAL(10,6) NULL,
  `Season` VARCHAR(30) NULL,
  `Rainfall_mm` DECIMAL(10,2) NULL,
  `Elevation_m` DECIMAL(10,2) NULL,
  `Slope_Degree` DECIMAL(10,2) NULL,
  `Soil_Type` VARCHAR(50) NULL,
  `NDVI` DECIMAL(10,3) NULL,
  `Temperature_C` DECIMAL(6,2) NULL,
  `Humidity` DECIMAL(6,2) NULL,
  `Distance_to_River_km` DECIMAL(10,2) NULL,
  `Land_Use` VARCHAR(50) NULL,
  `Historical_Landslide_Count` INT NULL,
  `Landslide_Occurred` VARCHAR(10) NULL,
  `Landslide_Risk` VARCHAR(20) NULL,
  `Casualties` INT NULL,
  `Injured` INT NULL,
  `Missing_Persons` INT NULL,
  `Families_Affected` INT NULL,
  `Population_Affected` INT NULL,
  `Houses_Damaged` INT NULL,
  `Roads_Blocked_km` DECIMAL(10,2) NULL,
  `Bridges_Damaged` INT NULL,
  `Economic_Loss_INR` DECIMAL(15,2) NULL,
  `Cropland_Damaged` DECIMAL(12,2) NULL,
  `Livestock_Lost` INT NULL,
  `Response_ID` VARCHAR(20) NULL,
  `Response_Time_Min` DECIMAL(10,2) NULL,
  `Rescue_Duration_Hours` DECIMAL(10,2) NULL,
  `Human_Resources_Deployed` INT NULL,
  `Rescue_Teams` INT NULL,
  `NDRF_Teams` INT NULL,
  `SDRF_Teams` INT NULL,
  `Volunteers` INT NULL,
  `Ambulances` INT NULL,
  `Helicopters` INT NULL,
  `Excavators` INT NULL,
  `JCB_Machines` INT NULL,
  `Cranes` INT NULL,
  `Relief_Camps` INT NULL,
  `Evacuated_People` INT NULL,
  `Aid_Amount_INR` DECIMAL(15,2) NULL,
  `Relief_Materials_Tons` DECIMAL(10,2) NULL,
  `Compensation_Provided` VARCHAR(10) NULL,
  `Recovery_Days` INT NULL,
  `Power_Outage_Hours` DECIMAL(10,2) NULL,
  `Water_Supply_Disrupted` VARCHAR(10) NULL,
  `Communication_Disruption` VARCHAR(10) NULL,
  `loaded_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`raw_id`),
  KEY `idx_raw_data_event_id` (`Event_ID`),
  KEY `idx_raw_data_response_id` (`Response_ID`),
  KEY `idx_raw_data_date` (`Date`),
  KEY `idx_raw_data_state_district` (`State`, `District`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
